# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
encoding:         utf-8
title:            Andrew Ladd
tagline:          'Computer Engineer in Training'
description:      "Student & Software Developer"
quote:            A mish-mash of so many colours of thought it's a surprise I see in more than just shades of brown.
future:           false


url:              http://www.andrewladd.co
baseurl:          /
paginate_path:    "/blog/page:num/"

author:
  name:           'Andrew Ladd'
  url:            https://ca.linkedin.com/in/andrew-ladd-9b3852a2
  resume:         public/Andrew_Ladd_2016.pdf

paginate: 5

# Custom vars
version:          0.0.1
gems:             [jekyll-paginate]

github:
  repo:           https://github.com/andrewladd/andrewladd.github.io
