# Site settings
title: Andrew's Thoughts
email: a_b_l@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  This is the description. It is here that I summarize the purpose of
  this blog and the overarching theme encompassing all articles.
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://andrewladd.co" # the base hostname & protocol for your site
twitter_username: tweet_meh
github_username:  andrewladd

# Build settings
markdown: kramdown
